### ISSUE TITLE
Error when importing

### ISSUE THREAD

**Issue by jeremyglebe** [CrezTheHomie/Saga-Of-The-Goblin-Horde#3]
![image](https://github.com/CrezTheHomie/Saga-Of-The-Goblin-Horde/assets/25252042/e4c17cf5-6771-496a-a2aa-f5894aa371e8)

**Comment by kevinrineer** [comment]
Hi Jeremy! 

Hmm I haven't looked at this project in a while, so I'll do some testing this weekend to see if I can push out a new version that will fix your issue!

Thank you for letting me know about this.

**Comment by kevinrineer** [comment]
Full error message on console:

`module "Saga-Of-The-Goblin-Horde" uses pack.private which has been replaced with pack.ownership
Module validation errors:
  packs: 
    0: Duplicate Compendium name "sotgh-bestiary" already declared by some other pack
    1: Duplicate Compendium name "sotgh-bestiary" already declared by some other pack
    2: Duplicate Compendium name "sotgh-bestiary" already declared by some other pack
    3: Duplicate Compendium name "sotgh-bestiary" already declared by some other pack`

**Comment by kevinrineer** [comment]
Okay the differences between Foundry v9 and Foundry v11 are quite massive.

Saving this for further reference [NeDB to LevelDB change](https://foundryvtt.com/article/v11-leveldb-packs/)

I will not be able to do this in 1 weekend and perhaps may not be able to do this at all in a reasonable time.

**Comment by kevinrineer** [comment]
I believe this should be fixed in [version 1.1.9]( https://github.com/CrezTheHomie/Saga-Of-The-Goblin-Horde/releases/tag/1.1.9)
